### ISSUE TITLE
Indentation loss on markdown-style list usage

### ISSUE THREAD

**Issue by JakeWharton** [ajalt/clikt#215]
```kotlin
private val configs by argument("CONFIG")
    .copy(help = """
      |YAML file containing list of coordinates to watch
      |
      |Format:
      |
      |coordinates:
      | - com.example.ping:pong
      | - com.example.fizz:buzz
      |""".trimMargin())
    .path(fs)
    .multiple(required = true)
```
produces:
```
Arguments:
  CONFIG  YAML file containing list of coordinates to watch

          Format:

          coordinates:
 - com.example.ping:pong
 - com.example.fizz:buzz
```
